### ISSUE TITLE
compute_analysis

### ISSUE THREAD

**Issue by RaminVali** [RaminVali/spotify_rsm#2]
Compute analysis function 
Analyze previously-loaded data.

This function runs an analytical measure of your choice (mean, median, linear regression, etc...)
and returns the data in a format of your choice.

Each group member will do a "sub_analysis" on the data. So all 3 of us will be working on it. Each group member will contribute a part of the analysis feature enhancing the performance of the analysis package.

**Comment by RaminVali** [comment]
Helpful tutorial about packaging code, as recommended by Simeon
https://packaging.python.org/en/latest/tutorials/packaging-projects/

**Comment by soniagrebenisan** [comment]
Correlation analysis function and the start of the unit test for the function:
https://github.com/RaminVali/spotify_rsm/pull/7
