### ISSUE TITLE
Leave out Stripplot?

### ISSUE THREAD

**Issue by MeliDeMoya** [RaminVali/spotify_rsm#8]
Hi team,
I got the scatter plot to work, but as much documentation as I read on stripplot, i couldnt get the function for it to work as part of my script:

```
def plot_data_stripplot( mydf: pd.DataFrame, xvar: str, yvar:str, hue: str): 
    
    sns.stripplot(mydf, xvar, yvar, hue)
    plt.xlabel(xvar)
    plt.ylabel(yvar)
   
plt.savefig('Stripplot.pdf')
```

What baffles me is that this simple line of code works just fine:
`sns.stripplot(data=df, x= 'speechiness', y='album_album_type', hue= 'danceability')`

Should we just leave it out?

**Comment by RaminVali** [comment]
Hi Melissa!

You can define your function like this:

```
def plot_data_stripplot( mydf: pd.DataFrame, xvar: str, yvar:str, hue: str): 

    sns.stripplot(data=mydf, x=xvar, y=yvar, hue=hue)
    plt.xlabel(xvar)
    plt.ylabel(yvar)
plt.savefig('Stripplot.pdf')
```


Then you can call it like this:

`plot_data_stripplot(df, 'speechiness','album_album_type','danceability')`

sns.stripplot takes key word arguments, so the only change I made was to go data = df, x = xvar... you get the idea. :)
